### ISSUE TITLE
🐛 Auth - Unable to log into app after it closes / Unable to register

### ISSUE THREAD

**Issue by ghost** [SSWConsulting/SSW.Rewards#153] opened 2020-11-01 21:39 UTC
To: @jakebaylissssw
cc: @adamcogan , @matt-goldman ,@AndreasLengkeek, @ozdemir-mehmet, @wicksipedia, @nvhoanganh, @brydeno 

## Expected Behavior

I should be able to log into the app multiple times.

## Current Behavior

I can only log into the app once. After that, once it has closed, I just see the red spinner on the login screen. I need to delete the app then re-install it, in order to log in again.

## Possible Solution

This could be related to MSAL configuration (see https://github.com/SSWConsulting/SSW.Rewards/pull/125) but could also be to do with KeyChain configuration if the app bundle was modified.

## Steps to Reproduce

1. Install the app on iOS.
2. Log in.
3. Close the app (NOTE: swiping up doesn't always reproduce the issue, but restarting the device does).
4. Attempt to log in again.

[AB#57970](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/57970)

**Comment by AndreasLengkeek** [comment] 2021-09-16 22:52
The issue seems to have affected the signup process and new users are unable to create accounts

**Comment by jianganna7** [comment] 2022-04-03 11:42
@AndreasLengkeek As a new user, I have managed to register for an account in one go.

Also, I am not able to reproduce the current behaviour of the red spinner on the login screen. Instead, I have the app crashed in splash screen.

**Steps to Reproduce:**
1. Install the app on iOS.
2. Log in.
3. Close the app by restarting the physical device.
4. Attempt to open the app.
5. App crashed in splash screen (able to open the app and logs in after 5~6 continuous tries or 10 seconds)

*Note the tests were all done on iPhone 6s Plus.

**Comment by JackDevAU** [comment] 2022-04-05 00:49
Hi @jianganna7,

I checked with @jernejk, who tested logging in on his Android. 

He is still having the auth infinite loading issue.

**Comment by jernejk** [comment] 2022-04-05 01:12
If it helps, I also tried Windows Subsystem for Android (Windows 11) and it worked.

![image](https://user-images.githubusercontent.com/5943653/161658479-e3bd53d6-0f2b-41da-9bbd-f62d2b740fe5.png)
![image](https://user-images.githubusercontent.com/5943653/161658485-4b584ba2-40a6-4e9d-847c-dceb61c9489f.png)

In case you don't have an Android but have Windows 11, this might help you debug things.
https://jkdev.me/use-windows-subsystem-for-android-in-windows-11/

**Comment by jianganna7** [comment] 2022-04-05 01:58
> If it helps, I also tried Windows Subsystem for Android (Windows 11) and it worked.

Cool - that's good to know and thanks for helping out!

**Comment by jianganna7** [comment] 2022-04-05 02:42
> I checked with @jernejk, who tested logging in on his Android. He is still having the auth infinite loading issue.

Thanks for checking @JackDevAU 🥇 Ah yep I think that's because PR #176 still hasn't been merged yet. 

BTW Did @jernejk reinstall the app for the last test, and was the internet stable when the error occurred? 

If needs to, we might ask @jernejk to test from [fix/infinite-loading](https://github.com/SSWConsulting/SSW.Rewards/tree/fix/infinite-loading)[](https://github.com/SSWConsulting/SSW.Rewards/tree/manage-dev-profiles) on his Android to see if it fixes the infinite loading issue from his end?

**Comment by JackDevAU** [comment] 2022-04-05 04:48
> Ah yep I think that's because PR https://github.com/SSWConsulting/SSW.Rewards/pull/176 still hasn't been merged yet.

Yep, once this is merged it should hopefully fix the issue. 

> BTW Did @jernejk reinstall the app for the last test, and was the internet stable when the error occurred?

No, he already had the app installed. 

Yea, once we merge the fix. Let's get JK to test it again 🙂

**Comment by JackDevAU** [comment] 2022-05-23 06:24
As per our conversation, we are also moving away from b2c to Identity.
Until this is fully implemented, we have provided a temporary fix, https://github.com/SSWConsulting/SSW.Rewards/pull/216

**Closed** 2022-05-23 06:24 UTC
Labels: bug, auth

**Comment by matt-goldman** [comment] 2022-05-23 06:26
> As per our conversation, we are also moving away from b2c to Identity. Until this is fully implemented, we have provided a temporary fix, #216
> 
> Please see the Identity issue here: #204

<img width="720" alt="image" src="https://user-images.githubusercontent.com/19944129/169756702-45e30181-25aa-49f3-8215-bca2221989a9.png">
**Figure: test pass from the product owner **
